### PR TITLE
Feature/add sqs

### PR DESCRIPTION
**Pull request by pm-mck**
Attempt at adding SQS support for #55

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
@pm-mck Are you still working on this? Some of your changes would be very useful to have to get #60 to work, since it suffers from the same problem with the generator, building invalid URLs.

**Comment by pm-mck** [comment]
@Leonidas-from-XIV I'm happy to keep working on this one, just hasn't had much momentum. I might have made the PR too big here :(

**Comment by tmcgilchrist** [comment]
I've hacked on this on another branch here https://github.com/inhabitedtype/ocaml-aws/pull/63 and made CI happy. @pm-mck

**Comment by tmcgilchrist** [comment]
Thanks I've merged this under https://github.com/inhabitedtype/ocaml-aws/pull/63

**Pull request closed without merging**
