### PR TITLE
Add update-version script and make rule

### PR DESCRIPTION
**Pull request by justanotherdot**
Similar to what's being done in #50. See [here](https://github.com/inhabitedtype/ocaml-aws/pull/50/files#diff-b67911656ef5d18c4ae36cb6741b7965R18).

I think there are a few more steps to this, @tmcgilchrist? From what I remember:

- [x] sed / awk something to find all the version numbers in *.opam files and change them
- [ ] `opam publish` - needs some hacking to tar.gz up each independent library

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
I'll get this merged as just the version numbers piece and we can do the package / opam publish step manually for now.

**Comment by seliopou** [comment]
Only one tarball should be necessary. Based on the name of the package that's being installed OPAM will use the appropriate OPAM file to figure out what to install. 

When I first started doing releases I think I overcomplicated stuff. Now for libraries like [angstrom](https://github.com/inhabitedtype/angstrom), [faraday](https://github.com/inhabitedtype/faraday), and [httpaf](https://github.com/inhabitedtype/httpaf) I just tag a single release and send a PR to the OPAM repository with OPAM files for all the packages that the repository provides. I have a script in a gist somewhere that I run to automate that. I'll find it and link it here.

**Comment by seliopou** [comment]
[Here's the gist](https://gist.github.com/seliopou/2e4beefda48551cfe41ae2a46bcd3ce6). The process is:

```
$ git checkout release
$ git reset --hard master
$ VERSION=<version> bash /path/to/release.sh
```

**Comment by tmcgilchrist** [comment]
Awesome, I'll make some time to try this out.

**Pull request merged**
